// Code generated by "stringer -type BgMode"; DO NOT EDIT

package main

import "fmt"

const _BgMode_name = "BgModeTextBgModeAffineBgModeAffineMap16BgModeAffineBitmapBgModeAffineBitmapDirectBgModeLargeBgMode3D"

var _BgMode_index = [...]uint8{0, 10, 22, 39, 57, 81, 92, 100}

func (i BgMode) String() string {
	if i < 0 || i >= BgMode(len(_BgMode_index)-1) {
		return fmt.Sprintf("BgMode(%d)", i)
	}
	return _BgMode_name[_BgMode_index[i]:_BgMode_index[i+1]]
}
