// Code generated by "stringer -type GxCmdCode"; DO NOT EDIT

package main

import "fmt"

const (
	_GxCmdCode_name_0 = "GX_NOP"
	_GxCmdCode_name_1 = "GX_MTX_MODEGX_MTX_PUSHGX_MTX_POPGX_MTX_STOREGX_MTX_RESTOREGX_MTX_IDENTITYGX_MTX_LOAD_4x4GX_MTX_LOAD_4x3GX_MTX_MULT_4x4GX_MTX_MULT_4x3GX_MTX_MULT_3x3GX_MTX_SCALEGX_MTX_TRANS"
	_GxCmdCode_name_2 = "GX_COLORGX_NORMALGX_TEXCOORDGX_VTX_16GX_VTX_10GX_VTX_XYGX_VTX_XZGX_VTX_YZGX_VTX_DIFFGX_POLYGON_ATTRGX_TEXIMAGE_PARAMGX_PLTT_BASE"
	_GxCmdCode_name_3 = "GX_DIF_AMBGX_SPE_EMIGX_LIGHT_VECTORGX_LIGHT_COLORGX_SHININESS"
	_GxCmdCode_name_4 = "GX_BEGIN_VTXSGX_END_VTXS"
	_GxCmdCode_name_5 = "GX_SWAP_BUFFERS"
	_GxCmdCode_name_6 = "GX_VIEWPORT"
	_GxCmdCode_name_7 = "GX_BOX_TESTGX_POS_TESTGX_VEC_TEST"
)

var (
	_GxCmdCode_index_0 = [...]uint8{0, 6}
	_GxCmdCode_index_1 = [...]uint8{0, 11, 22, 32, 44, 58, 73, 88, 103, 118, 133, 148, 160, 172}
	_GxCmdCode_index_2 = [...]uint8{0, 8, 17, 28, 37, 46, 55, 64, 73, 84, 99, 116, 128}
	_GxCmdCode_index_3 = [...]uint8{0, 10, 20, 35, 49, 61}
	_GxCmdCode_index_4 = [...]uint8{0, 13, 24}
	_GxCmdCode_index_5 = [...]uint8{0, 15}
	_GxCmdCode_index_6 = [...]uint8{0, 11}
	_GxCmdCode_index_7 = [...]uint8{0, 11, 22, 33}
)

func (i GxCmdCode) String() string {
	switch {
	case i == 0:
		return _GxCmdCode_name_0
	case 16 <= i && i <= 28:
		i -= 16
		return _GxCmdCode_name_1[_GxCmdCode_index_1[i]:_GxCmdCode_index_1[i+1]]
	case 32 <= i && i <= 43:
		i -= 32
		return _GxCmdCode_name_2[_GxCmdCode_index_2[i]:_GxCmdCode_index_2[i+1]]
	case 48 <= i && i <= 52:
		i -= 48
		return _GxCmdCode_name_3[_GxCmdCode_index_3[i]:_GxCmdCode_index_3[i+1]]
	case 64 <= i && i <= 65:
		i -= 64
		return _GxCmdCode_name_4[_GxCmdCode_index_4[i]:_GxCmdCode_index_4[i+1]]
	case i == 80:
		return _GxCmdCode_name_5
	case i == 96:
		return _GxCmdCode_name_6
	case 112 <= i && i <= 114:
		i -= 112
		return _GxCmdCode_name_7[_GxCmdCode_index_7[i]:_GxCmdCode_index_7[i+1]]
	default:
		return fmt.Sprintf("GxCmdCode(%d)", i)
	}
}
