// Code generated by "stringer -type TexFormat"; DO NOT EDIT

package raster3d

import "fmt"

const _TexFormat_name = "TexNoneTexA3I5Tex4Tex16Tex256Tex4x4TexA5I3TexDirect"

var _TexFormat_index = [...]uint8{0, 7, 14, 18, 23, 29, 35, 42, 51}

func (i TexFormat) String() string {
	if i < 0 || i >= TexFormat(len(_TexFormat_index)-1) {
		return fmt.Sprintf("TexFormat(%d)", i)
	}
	return _TexFormat_name[_TexFormat_index[i]:_TexFormat_index[i+1]]
}
